create table if not exists public.private_call_sessions (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  caller_id uuid not null references public.profiles(id) on delete cascade,
  callee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'ringing' check (status in ('ringing','connected','ended','declined')),
  offer jsonb,
  answer jsonb,
  created_at timestamptz not null default now(),
  ended_at timestamptz,
  check (caller_id <> callee_id)
);
create index if not exists private_call_sessions_participants_idx on public.private_call_sessions(caller_id,callee_id,created_at desc);

create table if not exists public.private_call_ice (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.private_call_sessions(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  candidate jsonb not null,
  created_at timestamptz not null default now()
);
create index if not exists private_call_ice_call_idx on public.private_call_ice(call_id,created_at);

alter table public.messages add column if not exists media_type text check (media_type is null or media_type in ('image','gif','video'));
alter table public.messages add column if not exists media_path text;
alter table public.messages add column if not exists media_url_external text;
alter table public.messages add column if not exists media_status text not null default 'approved' check (media_status in ('pending','approved','rejected'));

insert into storage.buckets (id,name,public) values ('private-chat','private-chat',false) on conflict (id) do nothing;

alter table public.private_call_sessions enable row level security;
alter table public.private_call_ice enable row level security;

create policy "private calls participants select" on public.private_call_sessions for select to authenticated using (auth.uid()=caller_id or auth.uid()=callee_id);
create policy "private calls caller insert" on public.private_call_sessions for insert to authenticated with check (auth.uid()=caller_id);
create policy "private calls participants update" on public.private_call_sessions for update to authenticated using (auth.uid()=caller_id or auth.uid()=callee_id) with check (auth.uid()=caller_id or auth.uid()=callee_id);
create policy "private call ice participants read" on public.private_call_ice for select to authenticated using (exists (select 1 from public.private_call_sessions c where c.id=call_id and (c.caller_id=auth.uid() or c.callee_id=auth.uid())));
create policy "private call ice participant insert" on public.private_call_ice for insert to authenticated with check (sender_id=auth.uid() and exists (select 1 from public.private_call_sessions c where c.id=call_id and (c.caller_id=auth.uid() or c.callee_id=auth.uid())));

create policy "private chat media participants read" on storage.objects for select to authenticated using (bucket_id='private-chat' and exists (select 1 from public.conversations c where c.id::text=split_part(name,'/',1) and (c.user_a=auth.uid() or c.user_b=auth.uid())));
create policy "private chat media own upload" on storage.objects for insert to authenticated with check (bucket_id='private-chat' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "private chat media own delete" on storage.objects for delete to authenticated using (bucket_id='private-chat' and (storage.foldername(name))[1]=auth.uid()::text);

create table if not exists public.speed_dating_queue (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  active boolean not null default true
);
create table if not exists public.speed_dating_pairs (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  round_started_at timestamptz not null default now(),
  round_ends_at timestamptz not null,
  status text not null default 'active' check (status in ('active','ended')),
  liked_a boolean not null default false,
  liked_b boolean not null default false,
  created_at timestamptz not null default now(),
  check (user_a <> user_b)
);
create index if not exists speed_dating_pairs_users_idx on public.speed_dating_pairs(user_a,user_b,created_at desc);

alter table public.speed_dating_queue enable row level security;
alter table public.speed_dating_pairs enable row level security;
create policy "speed queue own" on public.speed_dating_queue for select to authenticated using (user_id=auth.uid());
create policy "speed pairs participant" on public.speed_dating_pairs for select to authenticated using (user_a=auth.uid() or user_b=auth.uid());
create policy "speed pair participant update likes" on public.speed_dating_pairs for update to authenticated using (user_a=auth.uid() or user_b=auth.uid()) with check (user_a=auth.uid() or user_b=auth.uid());

create or replace function public.speed_dating_join(p_mode text default 'join')
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare uid uuid := auth.uid(); now_local timestamp; dow int; mins int; q public.speed_dating_queue%rowtype; partner uuid; pair public.speed_dating_pairs%rowtype; existing public.speed_dating_pairs%rowtype;
begin
 if uid is null then raise exception 'Not authenticated'; end if;
 now_local := timezone('Europe/London', now()); dow := extract(isodow from now_local)::int; mins := extract(hour from now_local)::int*60 + extract(minute from now_local)::int;
 if dow not in (6,7) or mins < 1200 or mins >= 1230 then
   if p_mode='leave' then delete from public.speed_dating_queue where user_id=uid; return jsonb_build_object('ok',true,'state','left'); end if;
   insert into public.speed_dating_queue(user_id,active) values(uid,true) on conflict(user_id) do update set active=true, joined_at=coalesce(public.speed_dating_queue.joined_at,now());
   return jsonb_build_object('ok',true,'state','waiting','starts_at','20:00 Europe/London');
 end if;
 if p_mode='leave' then delete from public.speed_dating_queue where user_id=uid; update public.speed_dating_pairs set status='ended',ended_at=now() where status='active' and (user_a=uid or user_b=uid); return jsonb_build_object('ok',true,'state','left'); end if;
 update public.speed_dating_pairs set status='ended' where status='active' and round_ends_at <= now() and (user_a=uid or user_b=uid);
 insert into public.speed_dating_queue(user_id,active) values(uid,true) on conflict(user_id) do update set active=true;
 select * into existing from public.speed_dating_pairs where status='active' and round_ends_at>now() and (user_a=uid or user_b=uid) order by round_started_at desc limit 1;
 if existing.id is not null then return jsonb_build_object('ok',true,'state','paired','pair_id',existing.id,'partner_id',case when existing.user_a=uid then existing.user_b else existing.user_a end,'round_ends_at',existing.round_ends_at); end if;
 select q.user_id into partner from public.speed_dating_queue q where q.active and q.user_id<>uid and not exists (select 1 from public.speed_dating_pairs p where p.status='active' and (p.user_a=q.user_id or p.user_b=q.user_id)) and not exists (select 1 from public.speed_dating_pairs p where p.user_a=least(uid,q.user_id) and p.user_b=greatest(uid,q.user_id)) order by q.joined_at limit 1 for update skip locked;
 if partner is null then return jsonb_build_object('ok',true,'state','waiting'); end if;
 insert into public.speed_dating_pairs(user_a,user_b,round_started_at,round_ends_at) values(least(uid,partner),greatest(uid,partner),now(),now()+interval '2 minutes') returning * into pair;
 return jsonb_build_object('ok',true,'state','paired','pair_id',pair.id,'partner_id',partner,'round_ends_at',pair.round_ends_at);
end; $$;
revoke all on function public.speed_dating_join(text) from public,anon;
grant execute on function public.speed_dating_join(text) to authenticated;

alter table public.private_call_sessions replica identity full;
alter table public.private_call_ice replica identity full;
alter table public.speed_dating_pairs replica identity full;
